// Test generated by RoostGPT for test golang-crud-api using AI Type Open AI and AI Model gpt-4-1106-preview

func (s *service) FindByCategory(category string) ([]AllProduct, error) {
    books, err := s.repository.FindByCategory(category)
    return books, err
    // return s.repository.FindAll() - commented out alternative
}

