// Test generated by RoostGPT for test golang-crud-api using AI Type Open AI and AI Model gpt-4-1106-preview


UpdateByNameProduct(name_product string, price string, email_user string, allProductRequest AllProductRequest) (AllProduct, error)

