// Test generated by RoostGPT for test golang-crud-api using AI Type Open AI and AI Model gpt-4-1106-preview


package laptop_test

import (
	"errors"
	"gorm.io/gorm"
	"testing"

	"github.com/stretchr/testify/assert"
	"gorm.io/driver/sqlite"
	"laptop"
)

type MockDB struct {
	ShouldReturnError bool
}

func (db *MockDB) Find(dest interface{}, conds ...interface{}) *gorm.DB {
	if db.ShouldReturnError {
		return &gorm.DB{Error: errors.New("mock db find error")}
	}

	laptops := dest.(*[]laptop.Laptop)
	*laptops = append(*laptops, laptop.Laptop{ID: 1, Brand: "Test Brand", Model: "Test Model"})
	return &gorm.DB{Error: nil}
}

func TestFindAll(t *testing.T) {
	// Positive Case
	mockDb := &MockDB{ShouldReturnError: false}
	repo := laptop.NewRepository(mockDb)
	laptops, err := repo.FindAll()
	assert.NoError(t, err)
	assert.NotEmpty(t, laptops)

	// Negative Case
	mockDb.ShouldReturnError = true
	_, err = repo.FindAll()
	assert.Error(t, err)
}

