// Test generated by RoostGPT for test golang-crud-api using AI Type Open AI and AI Model gpt-4-1106-preview

package laptop_test

import (
	"gorm.io/driver/sqlite"
	"gorm.io/gorm"
	"laptop"
	"testing"
)

func TestNewRepository(t *testing.T) {
	// Positive case: database connection is established successfully
	t.Run("returnsRepositoryWhenDBConnectionIsSuccessful", func(t *testing.T) {
		db, err := gorm.Open(sqlite.Open("file::memory:?cache=shared"), &gorm.Config{})
		if err != nil {
			t.Fatalf("could not open database: %v", err)
		}
		repo := laptop.NewRepository(db)
		if repo == nil {
			t.Errorf("expected new repository, got nil")
		}
	})

	// Negative case: database connection fails
	t.Run("returnsErrorWhenDBConnectionFails", func(t *testing.T) {
		_, err := gorm.Open(sqlite.Open("file:nonexistent?mode=memory&cache=shared"), &gorm.Config{})
		if err == nil {
			t.Errorf("expected error when opening database, got nil")
		}
	})
}

