// Test generated by RoostGPT for test golang-crud-api using AI Type Open AI and AI Model gpt-4-1106-preview


package laptop_test

import (
	"github.com/stretchr/testify/assert"
	"gorm.io/driver/sqlite"
	"gorm.io/gorm"
	"laptop"
	"testing"
)

func setupDB() *gorm.DB {
	db, err := gorm.Open(sqlite.Open("test.db"), &gorm.Config{})
	if err != nil {
		panic("failed to connect database")
	}
	// Migrate the schema
	db.AutoMigrate(&laptop.Laptop{})
	return db
}

func TestNewRepository(t *testing.T) {
	// Positive case
	db := setupDB()
	defer db.Migrator().DropTable(&laptop.Laptop{})

	repo := laptop.NewRepository(db)
	assert.NotNil(t, repo)

	// Negative case (simulating DB connection failure by passing nil)
	repo = laptop.NewRepository(nil)
	assert.Nil(t, repo)
}

