// Test generated by RoostGPT for test golang-crud-api using AI Type Open AI and AI Model gpt-4-1106-preview


package hoodie_test

import (
	"hoodie"
	"testing"

	"gorm.io/driver/sqlite"
	"gorm.io/gorm"
)

func TestNewRepository(t *testing.T) {
	// Positive case
	t.Run("Creates new repository successfully", func(t *testing.T) {
		db, err := gorm.Open(sqlite.Open("file::memory:?cache=shared"), &gorm.Config{})
		if err != nil {
			t.Fatalf("Failed to connect to the database: %v", err)
		}

		_, err = db.Migrator().CreateTable(&hoodie.Hoodie{})
		if err != nil {
			t.Fatalf("Failed to create table: %v", err)
		}

		repo := hoodie.NewRepository(db)
		if repo == nil {
			t.Errorf("Expected new repository, but got nil")
		}
	})

	// Negative case
	t.Run("Creation fails with nil database", func(t *testing.T) {
		repo := hoodie.NewRepository(nil)
		if repo != nil {
			t.Errorf("Expected nil result for nil database, but got: %#v", repo)
		}
	})
}

