// Test generated by RoostGPT for test golang-crud-api using AI Type Open AI and AI Model gpt-4-1106-preview

func (r *repository) Create(transaction Transaction) (Transaction, error) {
    err := r.db.Create(&transaction).Error
    return transaction, err
}

