// Test generated by RoostGPT for test golang-crud-api using AI Type Open AI and AI Model gpt-4-1106-preview

package book_test

import (
	"golang_e-commerce_API/book"
	"testing"

	"gorm.io/driver/sqlite"
	"gorm.io/gorm"
)

func setupDatabase(t *testing.T) *gorm.DB {
	db, err := gorm.Open(sqlite.Open("file::memory:?cache=shared"), &gorm.Config{})
	if err != nil {
		t.Fatalf("Failed to connect to the database: %v", err)
	}
	return db
}

func TestNewRepository_Positive(t *testing.T) {
	db := setupDatabase(t)
	repo := book.NewRepository(db)
	if repo == nil {
		t.Fatalf("Expected non-nil repository, got nil")
	}
}

func TestNewRepository_Negative(t *testing.T) {
	repo := book.NewRepository(nil)
	if repo == nil {
		t.Fatalf("Expected non-nil repository even with nil db, got nil")
	}
}

